# 2D Numpy in Python

-----

In [ ]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

# Create a 2D Numpy Array

In [4]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
print(a)


# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
print(A)

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Other Attributes:size,number of dimensions,shape

In [7]:
# Show the numpy array size

print(A.size)

# Show the numpy array dimensions

print(A.ndim)

# Show the numpy array shape

print(A.shape)

9
2
(3, 3)


# Accessing different elements of a Numpy Array

In [13]:
# Access the element on the second row and third column

print(A[1, 2])

# Access the element on the second row and third column

print(A[1][2])

# Access the element on the first row and first column

print(A[0][0])

# Access the element on the first row and first and second columns

print(A[0][0:2])

# Access the element on the first and second rows and third column

print(A[0:2, 2])


23
23
11
[11 12]
[13 23]


# Basic Operations

In [33]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]])

# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]])

# Add X and Y

Z = X + Y
print('Add X and Y is :\n',Z)
print('\n')


# Create a numpy array Y

R = np.array([[2, 1], [1, 2]]) 

# Multiply R with 2

K = 2 * R
print('Multiply Y with 2 is :\n ',K)
print('\n')

# Create a numpy array Y

M = np.array([[2, 1], [1, 2]]) 

# Create a numpy array X

W = np.array([[1, 0], [0, 1]]) 

# Multiply M with W

J = M * W
print('Multiply X with Y is :\n',J)
print('\n')


# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])

# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])

# Calculate the dot product

C = np.dot(A,B)

print('The dot product is :\n',C)
print('\n')

# Calculate the sine of C

print('Calculate the sine of C :\n',np.sin(Z))
print('\n')


# Create a matrix C

E = np.array([[1,1],[2,2],[3,3]])
print(E)

# Get the transposed of E

print('The  the transposed matrix of E is :\n',E.T)





Add X and Y is :
 [[3 1]
 [1 3]]


Multiply Y with 2 is :
  [[4 2]
 [2 4]]


Multiply X with Y is :
 [[2 0]
 [0 2]]


The dot product is :
 [[0 2]
 [0 2]]


Calculate the sine of C :
 [[0.14112001 0.84147098]
 [0.84147098 0.14112001]]


[[1 1]
 [2 2]
 [3 3]]
The  the transposed matrix of E is :
 [[1 2 3]
 [1 2 3]]


-----

-------